//
//  Recipe.swift
//  SousChefAI
//
//  Recipe model generated by AI based on available ingredients
//

import Foundation

struct Recipe: Identifiable, Codable {
    let id: String
    var title: String
    var description: String
    var missingIngredients: [Ingredient]
    var steps: [String]
    var matchScore: Double
    var estimatedTime: String?
    var servings: Int?
    
    init(id: String = UUID().uuidString,
         title: String,
         description: String,
         missingIngredients: [Ingredient] = [],
         steps: [String],
         matchScore: Double,
         estimatedTime: String? = nil,
         servings: Int? = nil) {
        self.id = id
        self.title = title
        self.description = description
        self.missingIngredients = missingIngredients
        self.steps = steps
        self.matchScore = matchScore
        self.estimatedTime = estimatedTime
        self.servings = servings
    }
    
    /// Indicates if recipe can be made with only available ingredients
    var canMakeNow: Bool {
        missingIngredients.isEmpty
    }
    
    /// Category based on missing ingredients
    var category: RecipeCategory {
        if canMakeNow {
            return .scavenger
        } else if missingIngredients.count <= 2 {
            return .upgrader
        } else {
            return .shopping
        }
    }
}

enum RecipeCategory: String, CaseIterable {
    case scavenger = "The Scavenger"
    case upgrader = "The Upgrader"
    case shopping = "Shopping Required"
    
    var description: String {
        switch self {
        case .scavenger:
            return "Uses only your current ingredients"
        case .upgrader:
            return "Needs 1-2 additional items"
        case .shopping:
            return "Requires shopping trip"
        }
    }
}
